# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - binary: space
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/deta/pc-cli/cmd.spaceVersion={{ .Version }}
      - -X github.com/deta/pc-cli/cmd.platform={{ .Env.GOARCH }}-{{ .Env.GOOS }}
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
  - binary: space
    id: space-macos
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/deta/pc-cli/cmd.spaceVersion={{ .Version }}
      - -X github.com/deta/pc-cli/cmd.platform={{ .Env.GOARCH }}-{{ .Env.GOOS }}
    goos:
      - darwin
    goarch:
      - amd64
    hooks:
      post:
        - gon -log-level=info -log-json .gon-amd64.hcl
  - binary: space
    id: space-macos-arm
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/deta/pc-cli/cmd.spaceVersion={{ .Version }}
      - -X github.com/deta/pc-cli/cmd.platform={{ .Env.GOARCH }}-{{ .Env.GOOS }}
    goos:
      - darwin
    goarch:
      - arm64
    hooks:
      post:
        - gon -log-level=info -log-json .gon-arm64.hcl

archives:
  - format: zip
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      space-{{ .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
release:
  # will mark pre-release tags as pre-releases on GitHub
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"