name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.20.2"
          cache: true
      - name: Install Gon
        run: brew install mitchellh/gon/gon
      - name: Setup Apple Certificates
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.APPLE_APP_SIGN_CERTIFICATES_P12 }}
          p12-password: ${{ secrets.APPLE_APP_SIGN_CERTIFICATES_P12_PASSWORD }}
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_APP_SIGN_USERNAME: ${{ secrets.APPLE_APP_SIGN_USERNAME }}
          APPLE_APP_SIGN_PASSWORD: ${{ secrets.APPLE_APP_SIGN_PASSWORD }}